language: go
sudo: required

go:
  - "1.13"

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t diving .
  - docker tag diving $DOCKER_USERNAME/diving
  - docker push $DOCKER_USERNAME/diving
  - docker images